from dataclasses import dataclass, field

'''
Data class for representing a password generated by PasswordGenerator
'''
@dataclass
class Password:
    words: list = field(default_factory=lambda: [])
    emoticon: str = ""
    number: str = ""
    password: str = ""

    def addWord(self, word, category):
        self.words.append((word, category))
        self.password = self.password + word

    def addEmoticon(self, emoticon):
        self.emoticon = emoticon
        self.password = self.password + emoticon

    def addNumber(self, number):
        self.number = number
        self.password = self.password + number

    def __hash__(self):
        return hash(self.password)

    def __eq__(self, other):
        return self.password == other